import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { ICON_SHAPES, type IconName } from '../src/core/icon-shapes';

/**
 * Icons, drawn as SVG (NOTES §66).
 *
 * They were drawn with Views from §56.2 — each curve a run of short bars — and
 * the owner, with a post's action row: *"the icons look bad it looks weird like
 * 144p"*. The shapes are unchanged; the browser draws them now. The screenshot
 * is the real check of how they look; these hold the shapes to their box and
 * the drawing to its rules.
 */

const NAMES = Object.keys(ICON_SHAPES) as IconName[];
const glyphs = readFileSync('src/ui/glyphs.tsx', 'utf8');

describe('every icon', () => {
  it('has something to draw', () => {
    for (const name of NAMES) expect(ICON_SHAPES[name].length, name).toBeGreaterThan(0);
  });

  it('keeps its circles, rectangles and lines inside its 24-unit box', () => {
    for (const name of NAMES) {
      for (const s of ICON_SHAPES[name]) {
        if (s[0] === 'c') {
          const [, cx, cy, r] = s;
          expect(r, name).toBeGreaterThan(0);
          for (const v of [cx - r, cy - r, cx + r, cy + r]) expect(v >= 0 && v <= 24, `${name} ${s}`).toBe(true);
        } else if (s[0] === 'r') {
          const [, x, y, w, h] = s;
          expect(w > 0 && h > 0, name).toBe(true);
          for (const v of [x, y, x + w, y + h]) expect(v >= 0 && v <= 24, `${name} ${s}`).toBe(true);
        } else if (s[0] === 'l') {
          for (const v of s.slice(1) as number[]) expect(v >= 0 && v <= 24, `${name} ${s}`).toBe(true);
        }
      }
    }
  });

  it('has no line at 0,0 — a shape whose numbers were never read', () => {
    // The first photograph in §56.2: user-plus's lines had x1/y1/x2/y2 skipped
    // by the generator and landed in the corner.
    for (const name of NAMES) {
      for (const s of ICON_SHAPES[name]) {
        if (s[0] === 'l') expect((s.slice(1) as number[]).every((v) => v === 0), name).toBe(false);
      }
    }
  });

  it('has paths the browser can read: a move first, then only path commands and numbers', () => {
    for (const name of NAMES) {
      for (const s of ICON_SHAPES[name]) {
        if (s[0] !== 'p') continue;
        expect(s[1], name).toMatch(/^[Mm]/);
        expect(s[1], name).toMatch(/^[MmLlHhVvCcSsQqTtAaZz0-9.,\s-]+$/);
      }
    }
  });

  it('carries Lucide’s licence notice and says it is generated', () => {
    const src = readFileSync('src/core/icon-shapes.ts', 'utf8');
    expect(src).toContain('GENERATED by scripts/make-icon-shapes.ts');
    expect(src).toContain('ISC License');
    expect(src).toContain('Permission to use, copy, modify, and/or distribute this software');
    expect(src).toContain('Cole Bemis'); // the Feather icons' MIT notice
  });
});

describe('the drawing', () => {
  it('is one <svg> in Lucide’s 24-unit box, with round ends and joins', () => {
    expect(glyphs).toContain('viewBox="0 0 24 24"');
    expect(glyphs).toContain('strokeLinecap="round"');
    expect(glyphs).toContain('strokeLinejoin="round"');
    for (const tag of ['<path ', '<circle ', '<rect ', '<line ']) expect(glyphs, tag).toContain(tag);
  });

  it('keeps the line 1.75 at 24 and never under 1.5 on screen', () => {
    expect(glyphs).toContain('const STROKE = 1.75;');
    expect(glyphs).toContain('Math.max(1.5, STROKE * k) / k');
  });

  it('fills only when asked — a liked heart, a saved bookmark, a star', () => {
    expect(glyphs).toContain("fill={filled ? color : 'none'}");
  });

  it('is no longer boxes, and needs no package', () => {
    // The bars, rings and bands of §56.2–§57 are gone with their geometry.
    expect(glyphs).not.toContain('icon-geometry');
    expect(glyphs).not.toMatch(/rotate: `\$\{/);
    const pkg = readFileSync('package.json', 'utf8');
    expect(pkg).not.toMatch(/react-native-svg|lucide/);
  });

  it('is hidden from screen readers — the control around it carries the words', () => {
    expect(glyphs).toContain('importantForAccessibility="no-hide-descendants"');
    expect(glyphs).toContain('aria-hidden');
  });
});
