/**
 * Where Nomi's moving parts attach, as fractions of the layer size.
 *
 * GENERATED by scripts/make-nomi-assets.ts, in the same run that cuts
 * assets/nomi-*.webp. Do not edit by hand: these numbers describe those exact
 * images, and are only correct for them.
 */
export const NOMI_RIG = {
  "width": 305,
  "height": 380,
  "wingLeftPivot": [
    0.1082,
    0.5026
  ],
  "wingRightPivot": [
    0.8885,
    0.5026
  ],
  "eyeLine": 0.3377,
  "eyeRadius": 0.1197
} as const;
