/**
 * Nomi's props as pictures, and each picture's size in pixels.
 *
 * GENERATED by scripts/make-nomi-props.ts, in the same run that cuts
 * assets/nomi-prop-*.webp. Do not edit by hand: the sizes describe those
 * exact images. Where each prop sits is `PROP_PLACES` in src/core/nomi-props.ts.
 */
import type { ImageSourcePropType } from 'react-native';
import type { NomiProp } from '../core/nomi-props';
import book from '../../assets/nomi-prop-book.webp';
import lightbulb from '../../assets/nomi-prop-lightbulb.webp';
import magnifier from '../../assets/nomi-prop-magnifier.webp';
import pencil from '../../assets/nomi-prop-pencil.webp';
import cap from '../../assets/nomi-prop-cap.webp';
import nightcap from '../../assets/nomi-prop-nightcap.webp';
import heart from '../../assets/nomi-prop-heart.webp';
import mug from '../../assets/nomi-prop-mug.webp';
import sparkles from '../../assets/nomi-prop-sparkles.webp';

export const NOMI_PROP_ART: Record<NomiProp, { source: ImageSourcePropType; width: number; height: number }> = {
  book: { source: book, width: 261, height: 231 },
  lightbulb: { source: lightbulb, width: 158, height: 231 },
  magnifier: { source: magnifier, width: 213, height: 235 },
  pencil: { source: pencil, width: 171, height: 200 },
  cap: { source: cap, width: 284, height: 196 },
  nightcap: { source: nightcap, width: 256, height: 227 },
  heart: { source: heart, width: 164, height: 138 },
  mug: { source: mug, width: 209, height: 264 },
  sparkles: { source: sparkles, width: 184, height: 191 },
};
