/**
 * Where Nomi's moving parts attach, as fractions of the layer size.
 *
 * GENERATED by scripts/make-nomi-assets.ts, in the same run that cuts
 * assets/nomi-*.webp. Do not edit by hand: these numbers describe those exact
 * images, and are only correct for them.
 */
export const NOMI_RIG = {
  "width": 367,
  "height": 493,
  "wingLeftPivot": [
    0.1771,
    0.5761
  ],
  "wingRightPivot": [
    0.7984,
    0.6329
  ],
  "eyeLeftLine": 0.3355,
  "eyeRightLine": 0.4055,
  "eyeRadius": 0.1396
} as const;
