/**
 * GENERATED by scripts/make-icon-shapes.ts from lucide-static 1.48.0 — do
 * not edit by hand; change the script and run it again.
 *
 * Every icon the app draws, in a 24-unit box, as the shapes a stroke follows:
 * ['p', path] · ['c', cx, cy, r] · ['r', x, y, width, height, corner] ·
 * ['l', x1, y1, x2, y2]. src/core/icon-geometry.ts turns them into straight
 * pieces and src/ui/glyphs.tsx draws those as Views (NOTES §56.2).
 *
 * `nomi` is drawn for this app. The rest are Lucide's (https://lucide.dev),
 * under this notice:
 *
 * ISC License
 *
 * Copyright (c) 2026 Lucide Icons and Contributors
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 * ---
 *
 * The following Lucide icons are derived from the Feather project:
 *
 * airplay, alert-circle, alert-octagon, alert-triangle, aperture, arrow-down-circle, arrow-down-left, arrow-down-right, arrow-down, arrow-left-circle, arrow-left, arrow-right-circle, arrow-right, arrow-up-circle, arrow-up-left, arrow-up-right, arrow-up, at-sign, calendar, cast, check, chevron-down, chevron-left, chevron-right, chevron-up, chevrons-down, chevrons-left, chevrons-right, chevrons-up, circle, clipboard, clock, code, columns, command, compass, corner-down-left, corner-down-right, corner-left-down, corner-left-up, corner-right-down, corner-right-up, corner-up-left, corner-up-right, crosshair, database, divide-circle, divide-square, dollar-sign, download, external-link, feather, frown, hash, headphones, help-circle, info, italic, key, layout, life-buoy, link-2, link, loader, lock, log-in, log-out, maximize, meh, minimize, minimize-2, minus-circle, minus-square, minus, monitor, moon, more-horizontal, more-vertical, move, music, navigation-2, navigation, octagon, pause-circle, percent, plus-circle, plus-square, plus, power, radio, rss, search, server, share, shopping-bag, sidebar, smartphone, smile, square, table-2, tablet, target, terminal, trash-2, trash, triangle, tv, type, upload, x-circle, x-octagon, x-square, x, zoom-in, zoom-out
 *
 * The MIT License (MIT) (for the icons listed above)
 *
 * Copyright (c) 2013-present Cole Bemis
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

export type IconShape =
  | readonly ['p', string]
  | readonly ['c', number, number, number]
  | readonly ['r', number, number, number, number, number]
  | readonly ['l', number, number, number, number];

export const ICON_SHAPES = {
  nomi: [
    ["p","M4 4 8 7h8l4-3v9a8 8 0 0 1-16 0z"],
    ["c",9,12.5,2.5],
    ["c",15,12.5,2.5],
    ["l",9,12.5,9,12.5],
    ["l",15,12.5,15,12.5],
    ["p","m11 16.2 1 1.4 1-1.4"],
  ],
  search: [
    ["p","m21 21-4.34-4.34"],
    ["c",11,11,8],
  ],
  send: [
    ["p","M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z"],
    ["p","m21.854 2.147-10.94 10.939"],
  ],
  compose: [
    ["p","M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"],
    ["p","M18.375 2.625a1 1 0 0 1 3 3l-9.013 9.014a2 2 0 0 1-.853.505l-2.873.84a.5.5 0 0 1-.62-.62l.84-2.873a2 2 0 0 1 .506-.852z"],
  ],
  edit: [
    ["p","M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"],
    ["p","m15 5 4 4"],
  ],
  settings: [
    ["p","M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915"],
    ["c",12,12,3],
  ],
  more: [
    ["c",12,12,1],
    ["c",19,12,1],
    ["c",5,12,1],
  ],
  back: [
    ["p","m15 18-6-6 6-6"],
  ],
  forward: [
    ["p","m9 18 6-6-6-6"],
  ],
  down: [
    ["p","m6 9 6 6 6-6"],
  ],
  close: [
    ["p","M18 6 6 18"],
    ["p","m6 6 12 12"],
  ],
  plus: [
    ["p","M5 12h14"],
    ["p","M12 5v14"],
  ],
  check: [
    ["p","M20 6 9 17l-5-5"],
  ],
  heart: [
    ["p","M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5"],
  ],
  comment: [
    ["p","M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719"],
  ],
  share: [
    ["p","M12 2v13"],
    ["p","m16 6-4-4-4 4"],
    ["p","M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"],
  ],
  bookmark: [
    ["p","M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z"],
  ],
  photo: [
    ["r",3,3,18,18,2],
    ["c",9,9,2],
    ["p","m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"],
  ],
  camera: [
    ["p","M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z"],
    ["c",12,13,3],
  ],
  set: [
    ["r",8,8,14,14,2],
    ["p","M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"],
  ],
  streak: [
    ["p","M12 3q1 4 4 6.5t3 5.5a1 1 0 0 1-14 0 5 5 0 0 1 1-3 1 1 0 0 0 5 0c0-2-1.5-3-1.5-5q0-2 2.5-4"],
  ],
  emoji: [
    ["p","M15 10V9"],
    ["p","M16.472 15a6 6 0 01-8.943 0"],
    ["p","M9 10V9"],
    ["c",12,12,10],
  ],
  people: [
    ["p","M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"],
    ["p","M16 3.128a4 4 0 0 1 0 7.744"],
    ["p","M22 21v-2a4 4 0 0 0-3-3.87"],
    ["c",9,7,4],
  ],
  person: [
    ["p","M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"],
    ["c",12,7,4],
  ],
  addFriend: [
    ["p","M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"],
    ["c",9,7,4],
    ["l",19,8,19,14],
    ["l",22,11,16,11],
  ],
  everyone: [
    ["c",12,12,10],
    ["p","M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"],
    ["p","M2 12h20"],
  ],
  lock: [
    ["r",3,11,18,11,2],
    ["p","M7 11V7a5 5 0 0 1 10 0v4"],
  ],
  reply: [
    ["p","M20 18v-2a4 4 0 0 0-4-4H4"],
    ["p","m9 17-5-5 5-5"],
  ],
  trash: [
    ["p","M10 11v6"],
    ["p","M14 11v6"],
    ["p","M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"],
    ["p","M3 6h18"],
    ["p","M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"],
  ],
  report: [
    ["p","m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"],
    ["p","M12 9v4"],
    ["p","M12 17h.01"],
  ],
  block: [
    ["c",12,12,10],
    ["p","M4.929 4.929 19.07 19.071"],
  ],
  hide: [
    ["p","M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49"],
    ["p","M14.084 14.158a3 3 0 0 1-4.242-4.242"],
    ["p","M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143"],
    ["p","m2 2 20 20"],
  ],
  notes: [
    ["p","M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"],
    ["p","M14 2v5a1 1 0 0 0 1 1h5"],
    ["p","M10 9H8"],
    ["p","M16 13H8"],
    ["p","M16 17H8"],
  ],
  progress: [
    ["p","M5 21v-6"],
    ["p","M12 21V9"],
    ["p","M19 21V3"],
  ],
  link: [
    ["p","M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"],
    ["p","M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"],
  ],
  recent: [
    ["p","M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"],
    ["p","M3 3v5h5"],
    ["p","M12 7v5l4 2"],
  ],
  star: [
    ["p","M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z"],
  ],
  folder: [
    ["p","M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"],
  ],
  up: [
    ["p","m5 12 7-7 7 7"],
    ["p","M12 19V5"],
  ],
  moderation: [
    ["p","M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"],
  ],
} as const satisfies Record<string, readonly IconShape[]>;

export type IconName = keyof typeof ICON_SHAPES;
